// Emoji Plot's hand-written puzzles: a well-known anime told in emoji. Kept
// to famous titles so the game is about decoding, not obscure trivia.
export const EMOJI_PUZZLES = [
  { emoji: '🧱🧱🧱👹😱🗡️', title: 'Attack on Titan' },
  { emoji: '🍥🦊👦🍜🥷', title: 'Naruto' },
  { emoji: '🏴‍☠️👒🍖🌊🗺️', title: 'One Piece' },
  { emoji: '📓✍️💀🍎🕵️', title: 'Death Note' },
  { emoji: '👹🗡️👧🎋🌊', title: 'Demon Slayer' },
  { emoji: '👊🦲😐💪🦸', title: 'One Punch Man' },
  { emoji: '🏐🦅🧡🏫🔥', title: 'Haikyu!!' },
  { emoji: '⚗️🦾🧒🔥🦴', title: 'Fullmetal Alchemist: Brotherhood' },
  { emoji: '🧙‍♀️⏳🌸💐👴', title: "Frieren: Beyond Journey's End" },
  { emoji: '🕵️‍♂️👨‍👩‍👧🥜💣🕶️', title: 'Spy x Family' },
  { emoji: '👻✊🤞🍩🏫', title: 'Jujutsu Kaisen' },
  { emoji: '🤖👦😭🌅🧬', title: 'Neon Genesis Evangelion' },
  { emoji: '🚀🤠🎷🐕💰', title: 'Cowboy Bebop' },
  { emoji: '🐉🟠7️⃣🥋💥', title: 'Dragon Ball Z' },
  { emoji: '🍙📼👧🏠👻', title: 'Spirited Away' },
  { emoji: '☄️🔄👦👧🏙️', title: 'Your Name.' },
  { emoji: '⏰🔬🍌📱🔁', title: 'Steins;Gate' },
  { emoji: '🎹🎻😢🌸🎶', title: 'Your Lie in April' },
  { emoji: '🐱🚌🌳👧👧', title: 'My Neighbor Totoro' },
  { emoji: '🦸‍♂️🏫💥🥦✊', title: 'My Hero Academia' },
  { emoji: '⚔️🎮🗡️🏰💀', title: 'Sword Art Online' },
  { emoji: '🪚👦🐶😈🩸', title: 'Chainsaw Man' },
  { emoji: '🎤⭐👶👩‍🎤🔪', title: 'Oshi no Ko' },
  { emoji: '🍀👺📕🗡️🖤', title: 'Black Clover' },
  { emoji: '🎸🎤😰👧🌀', title: 'Bocchi the Rock!' },
  { emoji: '🍳🔥👨‍🍳🏫🍽️', title: 'Food Wars! Shokugeki no Soma' },
  { emoji: '🏀👻6️⃣🔵🏆', title: "Kuroko's Basketball" },
  { emoji: '🧑‍🌾⛏️🐺🧪🏗️', title: 'Dr. Stone' },
  { emoji: '💎✨💃👑🎴', title: 'Kaguya-sama: Love Is War' },
  { emoji: '🐢⛩️🧚🗾👧', title: 'Mushishi' },
  { emoji: '🎣👦🃏🤡🗺️', title: 'Hunter x Hunter' },
  { emoji: '👁️💥🧍‍♂️🧍🏙️', title: 'Mob Psycho 100' },
  { emoji: '🍣🎸💨👱‍♀️🛵', title: 'FLCL' },
  { emoji: '🏎️⛰️🍞🚗💨', title: 'Initial D' },
  { emoji: '🧜‍♀️🐟🌊🏠👦', title: 'Ponyo' },
  { emoji: '🧹🐈‍⬛🍞📦👧', title: "Kiki's Delivery Service" },
  { emoji: '🪐🧑‍🚀👨‍👦🚀🌕', title: 'Space Brothers' },
  { emoji: '🧙‍♂️🏰🔥🚶‍♀️👵', title: "Howl's Moving Castle" },
  { emoji: '🧟‍♂️🏫🧑‍🎓🩸🏃', title: 'High School of the Dead' },
  { emoji: '🐺🌕🍎🪙📈', title: 'Spice and Wolf' },
  { emoji: '🐺👸🌲🦌🏹', title: 'Princess Mononoke' },
  { emoji: '🦴🥩🧍‍♂️👹🗡️', title: 'Berserk' },
];
